on:
  push:
    branches:
      - main  
    tags:
      - "*.*.*"
name: Build and Release
jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build extension
        run: | 
          mkdir -p builds
          npx @vscode/vsce pack --out ./builds
      - name: Release
        uses:  softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: false
          files: builds/own-light-001-*.*.*.vsix
      - name: Clean up
        run: rm -rf ./builds
